# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: dev-backend-kong-ingress
#   namespace: dev-backend
#   annotations:
#     konghq.com/strip-path: "true"
# spec:
#   rules:
#   - host: dev-heal.infoviz.co
#     http:
#       paths:
#       - path: /microservice1
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: microservice1
#             port:
#               number: 80
#       - path: /microservice2
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: microservice2
#             port:
#               number: 80

apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: microservice1-kong
  namespace: dev-backend
route:
  paths:
  - /microservice1